### ISSUE TITLE
Thanks for this

### ISSUE THREAD

**Issue by Tsjippy** [Duke-Jones/signal_cli_on_raspi#1]
I get the error `bash: line 203: /home/pi/zipadd: No such file or directory`

when running it like this `sudo wget -O - https://raw.githubusercontent.com/Duke-Jones/signal_cli_on_raspi/main/signalupdate.sh | sudo bash`

**Comment by Duke-Jones** [comment]
You have to download both files "signalupdate.sh" and "zipadd" and then run the script. 
I've been wanting to merge this into one file for a long time, but haven't got round to it yet.

**Comment by Duke-Jones** [comment]
I have created the new version v1.0.1 - it no longer needs the "zipadd" file.
